import { generateKeyPairSync, randomUUID } from 'node:crypto';
import {
  mkdirSync, readFileSync, rmSync, writeFileSync,
} from 'node:fs';
import { join, resolve } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';

import {
  BASELINE_IDENTITY,
  generateLean,
  generateSmt2,
  githubOidcAudience,
  isRecognizedMusubixSource,
  legacySolverCommands,
  loadTrace,
  validateModelCorrespondenceEvidence,
} from '../packages/analysis/src/index.js';
import { install } from '../packages/cli/src/install.js';

const roots: string[] = [];
const repositoryRoot = resolve('.');

function temporaryRoot(name: string): string {
  const root = resolve('.test-work', `${name}-${randomUUID()}`);
  mkdirSync(root, { recursive: true });
  roots.push(root);
  return root;
}

function write(root: string, path: string, text: string): void {
  const target = join(root, path);
  mkdirSync(resolve(target, '..'), { recursive: true });
  writeFileSync(target, text);
}

afterEach(() => {
  for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true });
});

describe('current product-name guidance', () => {
  /** @id TEST-M5-WAVE1-PRODUCT-NAMING-001
   * @verifies REQ-M5-WAVE1-NAMING-001
   */
  it('TEST-M5-WAVE1-PRODUCT-NAMING-001 uses musubix5 at output boundaries and preserves legacy identities', async () => {
    const traceRoot = temporaryRoot('product-name-trace');
    await expect(loadTrace(traceRoot))
      .rejects.toThrow('Trace graph missing; run musubix5 trace build.');

    const consumerRoot = temporaryRoot('product-name-consumer');
    await install(consumerRoot, repositoryRoot, { feature: 'naming' });
    write(consumerRoot, '.musubix/features/naming/requirements.md', [
      '## REQ-NAMING-001: Name guidance',
      'Priority: must',
      'Type: functional',
      'Pattern: ubiquitous',
      'Statement: The system shall use the current product name.',
      'Acceptance: Generated guidance uses musubix5.',
      'Formal: {"kind":"temporal","trigger":"guidance_requested","response":"current_name_used","withinMs":1000}',
      '',
    ].join('\n'));

    const correspondence = await validateModelCorrespondenceEvidence(consumerRoot);
    const missingCorrespondence = correspondence.diagnostics
      .find((diagnostic) => diagnostic.code === 'MODEL_CORRESPONDENCE_MISSING');
    const quality = JSON.parse(
      readFileSync(join(consumerRoot, '.musubix/evidence/quality.json'), 'utf8'),
    ) as { reason: string };
    const smtHeader = generateSmt2({ literals: [] }).split('\n')[0];
    const leanHeader = generateLean({ literals: [], consistency: 'unknown' }).split('\n')[0];
    const outputs = [
      missingCorrespondence?.message,
      quality.reason,
      readFileSync(join(consumerRoot, '.gitignore'), 'utf8')
        .split(/\r?\n/).find((line) => line.includes('generated caches')),
      smtHeader,
      leanHeader,
    ];

    expect(outputs).toEqual([
      'Requirements with explicit Formal JSON require model correspondence evidence. '
        + 'Run `npx musubix5 evidence refresh` to generate .musubix/evidence/model-correspondence.json.',
      'No checks have run. Configure commands and run musubix5 gate.',
      '# musubix5 generated caches',
      '; Generated by musubix5. This checks only the documented explicit constraint model.',
      '/- Generated by musubix5.',
    ]);
    expect(outputs.every((output) => !output?.includes('musubix3'))).toBe(true);

    const baseline = JSON.parse(
      readFileSync(join(repositoryRoot, 'docs/baseline/musubix3-v0.1.18-cli-help.json'), 'utf8'),
    ) as { baseline: { package: string }; snapshots: Array<{ command: string; stdout: string }> };
    expect(baseline.baseline.package).toBe('musubix3');
    expect(baseline.snapshots[0]).toMatchObject({
      command: 'musubix3',
      stdout: expect.stringContaining('Usage: musubix3'),
    });
    expect(isRecognizedMusubixSource({
      name: 'musubix3',
      repository: { url: 'https://github.com/nahisaho/musubix3.git' },
    })).toBe(true);
    expect(legacySolverCommands({
      MUSUBIX3_Z3: '/legacy/z3',
      MUSUBIX3_LEAN: '/legacy/lean',
    })).toEqual({ z3: '/legacy/z3', lean: '/legacy/lean' });

    const publicKey = generateKeyPairSync('ed25519').publicKey
      .export({ type: 'spki', format: 'pem' }).toString();
    expect(githubOidcAudience('musubix5', 'key-id', 'legacy-key'))
      .toContain('#musubix3-key-id=');
    expect(githubOidcAudience('musubix5', 'public-key', 'legacy-key', publicKey))
      .toContain('#musubix3-key-sha256=');
    expect(BASELINE_IDENTITY.package).toBe('musubix3');
  });
});
