# Shared trace index stability design

## Scope

This design replaces committed per-feature trace copies with one portable
repository-wide committed index. It does not change annotation discovery, node
or edge meaning, coverage thresholds, impact traversal, or the public semantic
`TraceGraph` returned to callers.

## DES-M5-WAVE1-TRACE-001: Canonical shared index persistence
Responsibilities: Build one complete repository-wide semantic trace graph, canonicalize its persisted representation, and publish the same complete graph to the committed shared index and disposable cache without content-neutral rewrites.
Interfaces: `traceInputs(root)`; `buildTrace(root, persist)`; shared persistence helper used by trace build and install; semantic `TraceGraph`; committed `.musubix/trace/index.json`; gitignored `.musubix/cache/trace.json`; canonical serializer; semantic comparison excluding display-only fields; same-directory atomic `writeText` boundary; test-observable operation counter `trace.committedArtifactRewrites` that is not added to CLI or JSON output; authoritative test `TEST-M5-WAVE1-TRACE-STABILITY-001`.
Constraints: The shared index is schema version 2 with top-level fields in order `schemaVersion`, `kind`, `generatedAt`, `nodes`, `edges`, `diagnostics`, `fingerprints`; `kind` is exactly `repository-trace-index`, and `generatedAt` uses `YYYY-MM-DDTHH:mm:ss.sssZ`. It contains the complete repository graph, not a projection, and all stored paths are NFC portable repository-relative `/` paths compared by Unicode scalar value without locale. Canonical JSON is UTF-8, uses two-space indentation and one trailing LF, rejects unknown fields at every object level, orders fingerprint keys by the same path comparator, nodes by `(id, kind, path, line, mandatory-rank)` where absent/false/true rank `0/1/2`, edges by `(from, to, relation, occurrence)`, and diagnostics by `(code, severity, path-or-empty, line-or-zero, message, occurrence)`. Occurrence is an internal canonical ordering key for exact duplicate edges/diagnostics and is not added to the returned public records. Conflicts are the exact cases defined by REQ-M5-WAVE1-TRACE-002. Every repository trace-evidence writer must call this shared helper. The helper chooses one publication byte sequence: retain bytes when both valid targets are candidate-semantic-equal and byte-identical; otherwise prefer candidate-semantic-equal valid shared bytes, then valid cache bytes, otherwise serialize the candidate with one new timestamp. It replaces only targets differing from the selected bytes, so successful completion is byte-identical while an ordinary prior-success no-op preserves both mtimes. Changed outputs are atomically replaced independently. A write/rename failure on an existing target preserves its prior bytes and mtime; failure creating an absent target leaves it absent; both remove the staging file and return failure. If one target has already succeeded, its valid complete bytes remain, the overall operation fails, and legacy removal does not start until both current-format targets validate and are byte-identical. This explicit failure state may temporarily coexist with legacy v1 files but never creates feature-local v2 files and is never reported as successful completion. A semantic build can rewrite at most the one committed generated artifact; cache replacement is not counted by `trace.committedArtifactRewrites`.
Requirements: REQ-M5-WAVE1-TRACE-001 REQ-M5-WAVE1-TRACE-002
ADRs: ADR-0028

## DES-M5-WAVE1-TRACE-002: Shared-index loader, stale evaluation, and legacy migration
Responsibilities: Load the fastest complete stored graph, normalize persisted schema-v2 envelopes into the unchanged public schema-v1 `TraceGraph`, preserve stale-evidence evaluation, support legacy feature trace copies as read-only migration input, own the `trace.ts` missing-message token replacement, and remove obsolete copies only after successful shared-index publication.
Interfaces: `loadTrace(root)`; loader precedence `.musubix/cache/trace.json`, `.musubix/trace/index.json`, then sorted `.musubix/features/*/trace.json`; schema-v1 legacy `TraceGraph` reader; schema-v2 shared-index reader; `checkTrace(root, graph, strict, thresholds)`; `traceImpact(graph, query)`; integrated missing-trace contract `Trace graph missing; run musubix5 trace build.`; downstream `DES-M5-WAVE1-NAMING-001`; authoritative integration test `TEST-M5-WAVE1-TRACE-COMPAT-001`.
Constraints: Cache and shared index must each be complete graphs and are validated structurally before return. For schema-v2 input, `loadTrace` strips persistence-only `kind`, changes the returned `schemaVersion` to `1`, and returns exactly the unchanged public/in-memory `TraceGraph` fields `schemaVersion`, `generatedAt`, `nodes`, `edges`, `diagnostics`, and `fingerprints`; no consumer API or JSON result exposes `kind`. Schema-v1 legacy input is returned through the same normalized public shape. Loader validation establishes stored integrity only: it does not compare stored fingerprints or records with current authoritative inputs and does not run fresh extraction as a load precondition. A valid old graph therefore loads after current additions, edits, renames, or deletions. `checkTrace` is the sole currency boundary: after existing stored/structural diagnostics, it emits exactly one `TRACE_STALE_PATH` for each missing stored node in `(path, line, id)` order, followed by exactly one `TRACE_STALE` for each path whose stored/current fingerprint membership or value differs in portable path order; strict result is invalid/nonzero when either exists. If cache exists but is invalid, loading fails with its classified diagnostic and does not fall through. If cache is missing, the shared index is attempted; if shared index exists but is invalid, loading fails and does not fall through. Legacy fallback is used only when both current-format paths are missing. Each discovered legacy copy must be a structurally self-contained schema-v1 graph: required field types valid, node IDs unique, every edge endpoint present, and paths/fingerprints syntactically valid. All copies must have equal canonical semantic bytes after excluding `generatedAt`; otherwise loading fails closed. Legacy loading performs no cache population, migration write, or deletion. After `trace build` has atomically persisted and validated byte-identical current-format outputs, it deletes every `.musubix/features/*/trace.json` in sorted portable path order, regardless of Git tracked state; deletion failure is explicit, retains the valid current-format outputs and remaining legacy files, and permits retry. A fresh clone with no cache uses the committed shared index for strict check and impact. GitHub issue #25 and this component own the `packages/analysis/src/trace.ts` token replacement and exact final message `Trace graph missing; run musubix5 trace build.`; `DES-M5-WAVE1-NAMING-001` consumes and verifies that dependency-provided output but does not edit or implement it.
Requirements: REQ-M5-WAVE1-TRACE-002
ADRs: ADR-0028
Depends-On: DES-M5-WAVE1-TRACE-001

## DES-M5-WAVE1-TRACE-003: Installer and integration ownership
Responsibilities: Make installation produce one complete valid shared trace index, prevent mixed trace formats, and define deterministic regeneration ownership for candidate refresh and integration.
Interfaces: `install(root, packageRoot, options)` in `packages/cli/src/install.ts`; shared persistence helper from DES-M5-WAVE1-TRACE-001; install action for `.musubix/trace/index.json`; `.gitignore` entry `/.musubix/cache/`; legacy trace discovery/removal; generated-trace classification in `packages/analysis/src/release-manifest.ts`; integrator-owned migration documentation in `docs/migration-guide.md`, `README.md`, and `README-ja.md`; candidate refresh and integration verification workflow.
Constraints: Non-dry-run install writes normative requirements/design inputs before building trace content, then must call the shared persistence helper; no alternate installer serializer is permitted. It never writes `.musubix/features/<feature>/trace.json` or any feature-local schema-v2 file. Dry-run reports the shared-index and cache create/replace/unchanged actions plus sorted legacy removals without mutating files. Existing valid shared content is content-compared even under ordinary install, while `--force` may replace normative assets but does not force a semantically equal trace rewrite. Installation removes legacy feature traces only after both current-format outputs exist and validate. Successful completion leaves no mixed current/legacy format; an explicit publication or removal failure may retain legacy v1 files beside a valid current-format target for deterministic retry and must return nonzero. Generated trace/cache paths are not assignment-owned merge inputs: after each candidate refresh, the integrator discards candidate cache bytes, regenerates `.musubix/trace/index.json` and cache once from the refreshed tree, removes legacy feature traces, and then runs candidate verification. Repository release/snapshot generated-trace classification adds `.musubix/trace/index.json` while retaining the migration-era `.musubix/features/*/trace.json` predicate; the cache remains ignored and uncommitted. The integrator updates the named documentation paths and commits them before issue assignments are dispatched.
Requirements: REQ-M5-WAVE1-TRACE-001 REQ-M5-WAVE1-TRACE-002
ADRs: ADR-0028
Depends-On: DES-M5-WAVE1-TRACE-001 DES-M5-WAVE1-TRACE-002

## Verification and handoff

`TEST-M5-WAVE1-TRACE-STABILITY-001` proves no-op SHA-256/mtime/Git stability,
one committed rewrite maximum for a real-repository semantic change, cache
behavior, atomic failure preservation, and absence of feature trace writes.
`TEST-M5-WAVE1-TRACE-COMPAT-001` proves cache/shared/legacy precedence,
schema validation and public-v1 normalization, stale and missing-path
diagnostics, equal legacy fallback, install and dry-run behavior, migration
removal, a cache-free fresh clone, and the exact #25-owned post-rename
missing-trace message. Existing affected regression ownership includes
`tests/parallel-review-regressions.test.ts` for persisted cache schema and
installer behavior, `tests/parallel-final-findings-generation5.test.ts` for
legacy feature-trace workspace assumptions, and
`tests/trace-namespace.test.ts` for direct `buildTrace`/`checkTrace` semantics,
plus `tests/approval-scope.test.ts`, `tests/release-candidate-tree.test.ts`,
and `tests/release-manifest-scope.test.ts` for the additive shared-index and
retained migration-era generated-trace exclusions.
`tests/product-name-guidance.test.ts` is a verification-only dependency for the
final message and is not the implementation owner of `trace.ts`.
